### ISSUE TITLE
Inventories deleting!

### ISSUE THREAD

**Issue by Salkras** [Multiverse/Multiverse-Inventories#167] opened 2013-05-05 15:32 UTC
Hi,
Multiverse inventories works for sepeartating invenetories, but as soon as someone moves from one world to another it wipes there inventories and there are no errors in the console
(I am using MCPC)

**Comment by dumptruckman** [comment] 2017-06-07 17:09
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 17:09 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired
