### ISSUE TITLE
One-sided inventory teleportation

### ISSUE THREAD

**Issue by lifehome** [Multiverse/Multiverse-Inventories#178] opened 2013-06-10 13:38 UTC
Is it possible for players to only share the inventory when he/she goes through a multiverse-portal, and it would be seperated ever since?

To be accurate, for an example:

Tom goes through Portal Mortal2Upper, and the plugin syncs his inventory with the upper world. Afterward, his share group will be seperated from the Mortal world.

**Comment by dumptruckman** [comment] 2017-06-07 16:44
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 16:44 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired, Shares
