### ISSUE TITLE
MultiVerse Inv Folder Won't Create!

### ISSUE THREAD

**Issue by HoboCat34** [Multiverse/Multiverse-Inventories#177] opened 2013-06-08 15:53 UTC
I have reloaded and restarted my server several times! WONT WORK!

**Comment by dumptruckman** [comment] 2017-06-07 16:44
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 16:44 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired
