### ISSUE TITLE
Custom NBT tags not saved.

### ISSUE THREAD

**Issue by Jamie-Jm3** [Multiverse/Multiverse-Inventories#107] opened 2012-12-03 19:57 UTC
OK, so I have a plugin on my server that allows people to collect skulls, the server used many worlds so players are switching to and through each world. 

the issue I am having is when I have a custom NBT tagged item like a player skull with a skin if i were to swap worlds and swap back the head would revert to just a head no NBT tag. 

hope this can be fixed as its a huge issue

**Comment by dumptruckman** [comment] 2017-06-07 20:25
Duplicate of #266

**Closed by dumptruckman** 2017-06-07 20:25 UTC
