### ISSUE TITLE
[Request] Command to delete files of one world folder

### ISSUE THREAD

**Issue by G-m-K** [Multiverse/Multiverse-Inventories#20] opened 2012-02-10 19:17 UTC
```
[8:10pm] GmK: dumptruckman: is there any way you can add a command to wipe all files from a world?
[8:11pm] GmK: we have a challenge world, and reset it with mv-adventure
[8:11pm] GmK: and would like to clear peoples inventories inbetween resets as well
[8:11pm] GmK: the world is in its own group"
```

We would love to be able to delete the inventories files which are in a certain group.

In combination with MV-Adventure we would reset the map and also the player files in that group of MV-Inventories.

A command to do so would be awesome!

**Comment by dumptruckman** [comment] 2017-06-08 14:25
Duplicate of #77

**Closed by dumptruckman** 2017-06-08 14:25 UTC
Labels: Enhancement
