### ISSUE TITLE
NullPointerException on enable

### ISSUE THREAD

**Issue by Bloodrayne1995** [Multiverse/Multiverse-Inventories#279] opened 2016-01-31 20:23 UTC
_Version:_ **2.5-b383 till the latest(Build 400 on Jenkins)**

_Description:_
Hello,

i updated the plugin to the latest version of your Jenkins (Build: 400). After I got the error (see by "Log-Outputs") i roll back the plugin to b383. But the same error.
I look in your github-repository and find the failure on [Perm.java](https://github.com/Multiverse/Multiverse-Inventories/blob/master/src/main/java/com/onarandombox/multiverseinventories/util/Perm.java) on the method register(). It add the permissions but on error it crashes.
Maybe you can help me.

_Log-Outputs:_

On Enable:
`at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.NullPointerException
        at com.onarandombox.multiverseinventories.MultiverseInventories.onCommand(MultiverseInventories.java:215) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        ... 8 more`

On command /mvinv group:

`[21:13:26 WARN]: Unexpected exception while parsing console command "mvinv group"
org.bukkit.command.CommandException: Unhandled exception executing command 'mvinv' in plugin Multiverse-Inventories v2.5-b383
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.NullPointerException
        at com.onarandombox.multiverseinventories.MultiverseInventories.onCommand(MultiverseInventories.java:215) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        ... 8 more`

With best regards
EONA Bloodrayne
eona-minecraft.de

**Comment by TheIntelloBox** [comment] 2017-06-11 07:50
OnDisable there is the problem too.

**Comment by dumptruckman** [comment] 2017-06-12 03:44
Neither of those stack traces could possibly come from onEnable or onDisable. They're both from running a command. They both also indicate that there WAS an error on startup. But you need to show me that error.

**Comment by TheIntelloBox** [comment] 2017-06-12 16:34
Presently, I don't see this error now.

**Comment by dumptruckman** [comment] 2017-06-19 13:25
Closing due to lack of information to reproduce this.

**Closed by dumptruckman** 2017-06-19 13:25 UTC
Labels: Bug, Need More Information, Unconfirmed
