### ISSUE TITLE
Swapping enderchests

### ISSUE THREAD

**Issue by ArtificialTruth** [Multiverse/Multiverse-Inventories#165] opened 2013-04-17 18:40 UTC
Somehow when i died in the void in SkyBlock, i spawned in the main world (world in server.properties) and my enderchest switched with skyblock! So now my items from the main world are in the SkyBlock world in my enderchest!
Any1 know how to fix?

**Comment by dumptruckman** [comment] 2017-06-07 17:10
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 17:10 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired, Shares
