### ISSUE TITLE
Advancements Addon

### ISSUE THREAD

**Issue by sadindianboi** [Multiverse/Multiverse-Inventories#418] opened 2021-02-24 05:42 UTC
### Feature request

**Feature description**
I'd like to suggest an addon to have different advancements per group.

**How the feature is useful**
 My friends and I love separating our server into survival, creative, and manhunt. If advancements are separated with it, we could keep the aspects of survival minecraft in one world and keep an essential part of manhunt in that world.

**Comment by nicegamer7** [comment] 2021-02-24 05:45
I'm closing this as a duplicate of #340. There is a test build available in the last comment of #363 with this functionality.

**Closed by nicegamer7** 2021-02-24 05:45 UTC
