### ISSUE TITLE
Custom items get renamed when changing worlds

### ISSUE THREAD

**Issue by theadopolomc** [Multiverse/Multiverse-Inventories#270] opened 2015-08-29 19:52 UTC
When a player on my server goes to the plot world, then back to the normal world all named items are made back to default items! So the items that plugins use, like CrackShot for guns, don't work anymore. It's really annoying because I keep getting complaints about reset items!

**Comment by dumptruckman** [comment] 2017-06-07 04:16
If this plugin gets revived, this will get fixed with the shift back to YAML data.

**Comment by xtechgamer735** [comment] 2017-07-09 14:11
Unable to reproduce this - items retain their custom names when moving between worlds

**Comment by dumptruckman** [comment] 2017-07-09 14:51
Closing this since it is old and probably fixed in the latest dev builds.

**Closed by dumptruckman** 2017-07-09 14:51 UTC
Labels: Minor Bug
