### ISSUE TITLE
Feature Request - Per-world Inventory commands

### ISSUE THREAD

**Issue by m-spry** [Multiverse/Multiverse-Inventories#63] opened 2012-06-02 19:43 UTC
A awesome feature to see in this is to type something like 

/mvinv open _player_ _world_

and bam you have access to the players inventory in said world, this can be used as an admin tool for preventing theft. a plugin like this is "Openinv" but it only allows the one world the player was in and is buggy in multiverse servers.

Another command that could prove useful.

/mvinv give _player_ _world_

THe ability to give a user an item in a world, it would work as if you were opening there .yml file and adding a line in but this one would be from within the game, its more useful than a standard give since normal /give commands only give the to the player if A) they are online and B) don't allow to choose a world for multiverse servers. 

These commands could improve how the game works with multiverse. This request is basically a request of commands that already exist but don't work well with multiverse servers. Thanks for reading.

**Comment by dumptruckman** [comment] 2017-06-08 14:16
Duplicate of #274

**Closed by dumptruckman** 2017-06-08 14:16 UTC
Labels: Accepted, Suggestion
