### ISSUE TITLE
Banners cause error in deserialization

### ISSUE THREAD

**Issue by gibbswe** [Multiverse/Multiverse-Inventories#259] opened 2015-01-17 13:50 UTC
Hi! Getting this error when users change worlds: http://pastebin.com/yV6me2N1

**Comment by Trojaner25** [comment] 2015-02-10 19:27
Error occurred while enabling <b>Achievements</b> v2.0.1-SNAPSHOT-71 (Is it up to date?)

This has nothing to do with Multiverse?

**Comment by gibbswe** [comment] 2015-03-01 09:25
Sorry about that @Trojaner25, pasted wrong error. Same link, new error! (:

**Comment by dumptruckman** [comment] 2017-06-07 13:17
Closing as duplicate of #252.

**Closed by dumptruckman** 2017-06-07 13:17 UTC
Labels: Duplicate
