### ISSUE TITLE
[Feature Request] Add item to certain world's inventory 

### ISSUE THREAD

**Issue by HeroCC** [Multiverse/Multiverse-Inventories#220] opened 2014-02-02 16:50 UTC
I am hoping for a command that adds an item to a player's world inventory. I was thinking something like this: /mvinv give <Player> <World> <Item ID> <Amount>

And that gives Player in World amount of Item. It would be useful for voting rewards, and many other scenarios. Thanks!

**Comment by dumptruckman** [comment] 2017-06-07 14:14
Duplicate of #274.

**Closed by dumptruckman** 2017-06-07 14:14 UTC
