### ISSUE TITLE
Need help, convert the native minecraft playerdata into MV-I's JSON format

### ISSUE THREAD

**Issue by imfrea** [Multiverse/Multiverse-Inventories#352] opened 2020-03-16 04:14 UTC
I have two existed servers, I want to merge them info ones with Multiverse-Inventories
how can I batch read the offline players' data to Multiverse-Inventories self's format?
(then I drop these data into the correct group's folder)
or if any other ways better?

**Comment by nicegamer7** [comment] 2020-05-14 04:45
This is a duplicate of #88.

**Closed by nicegamer7** 2020-05-14 04:45 UTC
