### ISSUE TITLE
Do Multiverse attributes still not work (health)

### ISSUE THREAD

**Issue by Kyle12421** [Multiverse/Multiverse-Inventories#507] opened 2022-09-10 23:57 UTC
Hello! I was wondering if Multiverse attributes were still broken (most importantly health). If so, is there any way to separate health from word to world without using Multiverse?

**Comment by benwoo1110** [comment] 2022-12-31 09:51
Duplicate of #492

**Closed by benwoo1110** 2022-12-31 09:51 UTC
Labels: Type: Assistance
