### ISSUE TITLE
Multiverse erased inventories

### ISSUE THREAD

**Issue by Weaponz** [Multiverse/Multiverse-Inventories#158] opened 2013-03-22 01:01 UTC
After every reset, Multiverse inv seems to be resetting inventories for my main worlds ("spawn, survival" and the nethers_ however it seems to be keeping the SkyBlock worlds inventories.

Plugin list: (1.5)

AntiInvisible, Backup, Vault, VoteLink, Wither, uSkyBlock, AutoMessage, SurvivalGames, SuperLogger, ProtocolLib, LoginSecurity, Votifier, mcMMO, Jobs, HideStream, KeepXP, WorldEdit, PermissionsBukkit, ColouredMotd, TNT, PlayerHeads, MyCommand, Paintball, NoAccountHack, WorldGuard, iConomy, CoreProtect, MonsterFix, ItemGamble, ClearLag, Suit, AutoSaveWorld, Simple Prefix, Essentials, ServerSigns, Enjin Minecraft Plugin, PlotMe, EssentialsChat, WGCustomFlags, EssentialsSpawn, VanishNoPacket, Factions, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, SimpleChestLock, Multiverse-Portals, ChestShop, BattleArena, ArenaSpleef, AntiCheat

Config:# Multiverse-Inventories Settings
# ===[ Multiverse Inventories Config ]===

settings:
  # This is the locale you wish to use.
  locale: en
  # If this is true it will generate world groups for you based on MV worlds.
  first_run: false
  # If this is set to true, it will enable bypass permissions (Check the wiki for more info.)
  use_bypass: false
  # If set to true, any world not listed in a group will automatically use the settings for the default group!
  default_ungrouped_worlds: false
  # The default and suggested setting for this is FALSE.
  # False means Multiverse-Inventories will not attempt to load or save any player data when they log in and out.
  # That means that MINECRAFT will handle that exact thing JUST LIKE IT DOES NORMALLY.
  # Changing this to TRUE will have Multiverse-Inventories save player data when they log out and load it when they log in.
  # The biggest potential drawback here is that if your server crashes, player stats/inventories may be lost/rolled back!
  save_load_on_log_in_out: false
  # If this is set to true, players will have different inventories/stats for each game mode.
  # Please note that old data migrated to the version that has this feature will have their data copied for both game modes.
  use_game_mode_profiles: false
shares:
  # When set to true, optional shares WILL be utilized in cases where a group does not cover their uses for a world.
  # An example of this in action would be an ungrouped world using last_location.  When this is true, players will return to their last location in that world.
  # When set to false, optional shares WILL NOt be utilized in these cases, effectively disabling it for ungrouped worlds.
  optionals_for_ungrouped_worlds: true
  # You must specify optional shares you wish to use here or they will be ignored.
  # The only built in optional share is "economy"
  use_optionals: []

**Comment by dumptruckman** [comment] 2017-06-07 17:51
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 17:51 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired
