### ISSUE TITLE
Error in 1.12

### ISSUE THREAD

**Issue by TheOtakuJames** [Multiverse/Multiverse-Inventories#309] opened 2017-06-13 02:28 UTC
Hi there, 
I'm having this error whenever someone goes to the nether or end of a world - https://codepaste.net/4ax9jf
Any ideas? It's quite spammy!!
Cheers,
~James

**Comment by dumptruckman** [comment] 2017-06-13 02:29
Duplicate of #296

**Closed by dumptruckman** 2017-06-13 02:29 UTC
