### ISSUE TITLE
Error While Building Configuration Map (skull-owner=null)

### ISSUE THREAD

**Issue by PinoyLifeCraft** [Multiverse/Multiverse-Inventories#277] opened 2016-01-17 01:39 UTC
[09:30:07 WARN]: [Multiverse-Inventories] Error while building configuration map
.
java.lang.NullPointerException: null value in entry: skull-owner=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(Coll
ectPreconditions.java:33) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135)
 ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:
206) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaSkull.serialize(Cra
ftMetaSkull.java:173) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(Craf
tMetaItem.java:850) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMa
p(JsonConfiguration.java:55) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMa
p(JsonConfiguration.java:56) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMa
p(JsonConfiguration.java:46) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMa
p(JsonConfiguration.java:46) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.saveToS
tring(JsonConfiguration.java:32) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.
save(EncodedJsonConfiguration.java:30) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.p
rocessProfileWrite(FlatFilePlayerData.java:243) [Multiverse-Inventories-2.5.jar:
?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.a
ccess$000(FlatFilePlayerData.java:30) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$F
ileWriteThread.run(FlatFilePlayerData.java:209) [Multiverse-Inventories-2.5.jar:
?]

**Comment by dumptruckman** [comment] 2017-06-07 04:41
Closing as duplicate of #266.

**Closed by dumptruckman** 2017-06-07 04:41 UTC
Labels: Bug, Need More Information, Unconfirmed
