### ISSUE TITLE
100+ mb .json files causing errors 

### ISSUE THREAD

**Issue by ryanogilvie** [Multiverse/Multiverse-Inventories#199] opened 2013-10-06 01:22 UTC
I have no idea how this happened and it only has happened recently to a few people and  I had been using the same version for a while. For an unknown reason the .json files for the two most active players amassed a size of   about 140,000 Kb opposed to the normal 1- 5kb files for everyone else. Everytime they switched worlds it would throw an out of memory error lagging the server (not crashing it) and failing to switch the inventories of only these players. I don't know how it managed to happen in the first place, but I managed to fix this by deleting the files.

Thanks

**Comment by dumptruckman** [comment] 2017-06-07 15:01
Duplicate of #208

**Closed by dumptruckman** 2017-06-07 15:01 UTC
