### ISSUE TITLE
Groups Keep Disappearing.

### ISSUE THREAD

**Issue by damnsatinist2** [Multiverse/Multiverse-Inventories#85] opened 2012-09-06 02:51 UTC
Every time I make a group (add worlds, shares, e.t.c) it works fine, however, upon server restarts, any group I created disappears.... except from the groups.yml. When I log on, the groups no longer function, and /mvinv list comes up with N/A. When I check all the server files, however, it is still in there. I don't know if anyone else is having/has had this problem. (If it helps, we're running tekkit)

**Comment by dumptruckman** [comment] 2017-06-08 13:39
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-08 13:39 UTC
Labels: Assistance, Bug, Old - Open new issue if desired, Unconfirmed
