### ISSUE TITLE
item Carryover by pressing "E" is not fixed!

### ISSUE THREAD

**Issue by ScuroK** [Multiverse/Multiverse-Inventories#323] opened 2018-01-05 11:43 UTC
Essentially it's just a matter of timing:

- Go into the Creative Mode world
- Load up your personal inventory with emerald blocks, spawn eggs, and all sorts of other goodies that completely throw off the economy and game-play in the Survival Mode world
- Warp, teleport, or use a Multiverse Portal to move into the Survival Mode world. Just as the world is changing over, hit the 'E' key to bring up your inventory GUI window.

How to (really) fix it?  Not by just closing inventory on teleport.

**Here is my idea:
Create some kind of "dummy inventory"
If a player changes the world this "dummy inventory" will load first.
Its function is to act as a transit inventory. If the player uses this bug, the cheated items go into this dummy inventory. Maybe you could even block the dropping of items there. but maybe thats not needed.
After a short delay the "dummy inventory" gets cleared and the real inventory loads.**

**Comment by dumptruckman** [comment] 2018-01-05 14:59
Duplicate of #161

**Closed by dumptruckman** 2018-01-05 14:59 UTC
