### ISSUE TITLE
Deserialization issue (MC 1.5 - CB#2647)

### ISSUE THREAD

**Issue by Puremin0rez** [Multiverse/Multiverse-Inventories#153] opened 2013-03-16 12:33 UTC
Getting this error quite frequently when switching between worlds which causes the previous worlds inventory to be moved to the next one (Last part is unconfirmed, a single user reported it... but I do see this error in console constantly.)

http://pastebin.com/nySmB2Hr

**Comment by dumptruckman** [comment] 2017-06-07 18:05
Probably a duplicate of #266

**Closed by dumptruckman** 2017-06-07 18:05 UTC
