### ISSUE TITLE
Could not pass event PlayerTeleportEvent and PlayerChangedWorldEvent

### ISSUE THREAD

**Issue by Mindrun** [Multiverse/Multiverse-Inventories#200] opened 2013-10-12 21:26 UTC
For the past few days, I've been getting a lot of Multiverse related errors, general problems with Multiverse and constant memory leaks. Here's the error I get whenever anyone switches worlds, their inventories are kept the same after they do and so some players have a creative inventory in a survival world and vice versa.

22:14:19 [SEVERE] Could not pass event PlayerTeleportEvent to Multiverse-Inventories v2.5-b357
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:47)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
        at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.teleport(CraftPlayer.java:386)
        at com.earth2me.essentials.Teleport.now(Teleport.java:99)
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:147)
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:113)
        at com.earth2me.essentials.commands.Commandhome.goHome(Commandhome.java:108)
        at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:75)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:135)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:505)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:372)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
        at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:527)
        at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:971)
        at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:882)
        at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:829)
        at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
        at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:230)
        at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
        at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
        at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:132)
        at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:592)
        at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:239)
        at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:481)
        at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:413)
        at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:132)
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(JsonConfiguration.java:184)
        at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.<init>(EncodedJsonConfiguration.java:20)
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:77)
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:269)
        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87)
        at com.onarandombox.multiverseinventories.InventoriesListener.playerTeleport(InventoriesListener.java:203)
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:47)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
        at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.teleport(CraftPlayer.java:386)
        at com.earth2me.essentials.Teleport.now(Teleport.java:99)
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:147)
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:113)
        at com.earth2me.essentials.commands.Commandhome.goHome(Commandhome.java:108)
        at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:75)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:135)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:505)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:372)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)

22:14:30 [SEVERE] Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v2.5-b357
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:47)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
        at net.minecraft.server.v1_6_R2.PlayerList.moveToWorld(PlayerList.java:479)
        at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.teleport(CraftPlayer.java:410)
        at com.earth2me.essentials.Teleport.now(Teleport.java:99)
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:147)
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:113)
        at com.earth2me.essentials.commands.Commandhome.goHome(Commandhome.java:108)
        at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:75)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:135)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:505)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:372)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
        at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:527)
        at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:971)
        at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:882)
        at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:829)
        at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
        at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:230)
        at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
        at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
        at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:132)
        at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:592)
        at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:239)
        at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:481)
        at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:413)
        at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by dumptruckman** [comment] 2017-06-07 15:00
Probably a duplicate of #208.

**Closed by dumptruckman** 2017-06-07 15:00 UTC
Labels: Duplicate
