### ISSUE TITLE
Issue with colors of name/lore of items

### ISSUE THREAD

**Issue by Ordrox** [Multiverse/Multiverse-Inventories#180] opened 2013-06-15 13:53 UTC
Craftbukkit version: 1.5.2-R1.0
Multiverse inventories version: devbuild #354
(The errors existed in other versions)

Hello there, just a found a issue with the color of the name and the lore of items.
here's an exemple:
![itemissue](https://f.cloud.github.com/assets/4704971/658145/b8ca54fe-d5bf-11e2-8394-c91c8dcacbed.png)

After some tests, that issue seems to appear like this:
1 - Player disconnect in world alpha
2 - The server restart
3 - Player connect, items in world alpha are okay.
4 - Player's items in world delta are all buged.
(the stuff isn't linked in these worlds)

The bug seems to repeat again and again and again (following the steps before) to get something like this:

First:
![itemissue1](https://f.cloud.github.com/assets/4704971/658159/d9753adc-d5c1-11e2-91b9-3bb2cbe12f28.png)

After several tries:
![itemissue2](https://f.cloud.github.com/assets/4704971/658160/e2c7da22-d5c1-11e2-801f-0ebd0146971e.png)

If it could help, the items are generated with RPGitems and Diablodrops.

**Comment by mcmyster** [comment] 2015-02-11 00:50
how do i fix this ? im really confused

**Comment by dumptruckman** [comment] 2017-06-07 16:43
Duplicate of #270

**Closed by dumptruckman** 2017-06-07 16:43 UTC
Labels: Duplicate
