### ISSUE TITLE
Fatal Crash

### ISSUE THREAD

**Issue by kingpyro** [Multiverse/Multiverse-Inventories#256] opened 2015-01-02 01:25 UTC
I'm getting a problem where the json file in the world folder for a player will sometimes go to like 300mb. The contents of a file seems to be duplicates of the same book in an inventory. This is causing mass lagg and sometimes crashing if the player opens their inventory or just logs in. Unknown how to replicate.

Crash log: http://pastebin.com/u520QJ59
/mv version -p: http://pastie.org/private/bmkdrhzdbfycxi0nvmsjqq#

**Comment by dumptruckman** [comment] 2017-06-07 13:07
Would have been useful to see the player data file as well. Not sure you can still help with this at this point. Also might be resolved in #305.

**Comment by xtechgamer735** [comment] 2017-07-09 14:10
Unable to reproduce this - as with #208 this is hard to test for but its not something I've come across in the past.

**Comment by dumptruckman** [comment] 2017-07-09 14:10
Closing since this is old and it may be fixed now. Open a new ticket if you have this problem with the latest dev builds.

**Closed by dumptruckman** 2017-07-09 14:10 UTC
Labels: Bug, Need More Information, Unconfirmed
