### ISSUE TITLE
Severe Error while enabling

### ISSUE THREAD

**Issue by EyMaddis** [Multiverse/Multiverse-Inventories#71] opened 2012-07-01 10:20 UTC
Hi there,
I use the most recent build from your jenkins (#167), but I had this with the release too:

I had disabled Multiverse Inventories for a long time, but when I want to enable it I get this sever error:

```
[INFO] [Multiverse-Inventories] Enabling Multiverse-Inventories v2.4-b167
[SEVERE] Error occurred while enabling Multiverse-Inventories v2.4-b167 (Is it up to date?)
java.lang.IllegalArgumentException: The permission multiverse.inventories.info is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:560)
        at com.onarandombox.multiverseinventories.util.Perm.register(Perm.java:196)
        at com.onarandombox.multiverseinventories.MultiverseInventories.onEnable(MultiverseInventories.java:87)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at com.alecgorge.minecraft.jsonapi.dynamic.APIWrapperMethods.enablePlugin(APIWrapperMethods.java:566)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:144)
        at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:85)
        at org.bukkit.craftbukkit.scheduler.CraftFuture.run(CraftFuture.java:34)
        at com.bergerkiller.bukkit.nolagg.examine.TimedWrapper.run(TimedWrapper.java:27)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:533)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
```

**Comment by aycgit** [comment] 2016-05-22 07:52
doesnt fix the issue i got the same problem

**Comment by sorifiend** [comment] 2016-05-22 07:57
Test again with no plugins other than multiverse inventories installed.

Also I highly recommend swapping to "per world inventory" plugin as soon as you can. It supports importing from this plugin: https://www.spigotmc.org/resources/per-world-inventory.4482/

**Comment by dumptruckman** [comment] 2017-06-08 13:49
Related to #18

**Comment by xtechgamer735** [comment] 2017-07-09 13:23
Unable to reproduce this

**Comment by dumptruckman** [comment] 2017-07-09 14:00
Closing since this is old and it may be fixed now. Open a new ticket if you have this problem with the latest dev builds.

**Closed by dumptruckman** 2017-07-09 14:00 UTC
Labels: Minor Bug, Unconfirmed
