### ISSUE TITLE
Request: Give Command

### ISSUE THREAD

**Issue by michaeldriskell** [Multiverse/Multiverse-Inventories#174] opened 2013-06-04 05:09 UTC
There should be a command that adds an item to a player's inventories in a certain world and when they're offline. This would be useful on servers where someone buys an item from the server's donation store (i.e. Skyblock) and it will put it in their inventory in the specified world.

**Comment by dumptruckman** [comment] 2017-06-07 16:47
Duplicate of #274.

**Closed by dumptruckman** 2017-06-07 16:47 UTC
