### ISSUE TITLE
Inventory-Files growing huge --> up to 2,3 GB

### ISSUE THREAD

**Issue by therealmccoy1234** [Multiverse/Multiverse-Inventories#208] opened 2013-12-19 22:05 UTC
I've had serious problems with multiverse inventory-files growing to huge sizes. I first realized the problem when the server started lagging and Memory starting to drop down and bounce up steadily. After a brief time of investigation I found out that the reason was a User teleporting from Spawnworld to plotworld. Looking into the Inventory-Directory showed, that his Inventory-file had grown to a size of 2,3 GB !!!! After deleting the File and restarting the Server everything went back to normal. Same thing happend with different users from time to time. Today I found out the cause for the incredible increase of filesize. The Problems are caused by plugins which save the Player-inventory to clear it, so that the Player can play the Plugins Minigame with empty inventory and afterwards they give the inventory back. This is what makes the files grow to such enormous dimensions. I've got 2 plugins on my Server that handle the Players-inventory like that. The plugins are HeavySpleef from Matzefratze und since a few days I got Quake installed from Geekpower14.

Would be great if you could fix that.

Greetings from Germany
and thank you for your work ;)

**Comment by dumptruckman** [comment] 2017-06-07 14:54
This will *possibly* be fixed in #305 but you revealed some information that makes me doubtful. If the cause it because of other plugins doing inventory handling then this may require some more finessing.

**Comment by dumptruckman** [comment] 2017-06-07 18:09
This is probably related to #266...

**Comment by xtechgamer735** [comment] 2017-07-09 14:02
Unable to reproduce this - it was always going to be difficult but I have never come across this issue.

**Comment by dumptruckman** [comment] 2017-07-09 14:09
Closing since this is old and it may be fixed now. Open a new ticket if you have this problem with the latest dev builds.

**Closed by dumptruckman** 2017-07-09 14:09 UTC
Labels: Bug, Critical
