### ISSUE TITLE
Multiverse-Inventories Give Command

### ISSUE THREAD

**Issue by unicxa** [Multiverse/Multiverse-Inventories#198] opened 2013-10-02 23:03 UTC
I found this and may i need a way to use the /give {player} <id> <amount> <world>
on my server alot like this.

https://forums.bukkit.org/threads/multiverse-inventories-give-command.132815/

**Comment by dumptruckman** [comment] 2017-06-07 15:02
Duplicate of #274

**Closed by dumptruckman** 2017-06-07 15:02 UTC
