### ISSUE TITLE
Suggestion: Database cleanup for old inventories

### ISSUE THREAD

**Issue by Portanna** [Multiverse/Multiverse-Inventories#308] opened 2017-06-09 18:46 UTC
Add option to **clean** old player's inventories in configuration, which will delete all multiverse-inventories data **older than x days**, as I've been using the plugin since 2015, and since then over 250.000 inventories have been stored, and I've noticed that only 7000 are those which were last-edited in 2017 (so those being the only active ones).

This way every mv-inventories inventory that was edited more than x days from now would be deleted and the inventory database would be **much cleaner and easier to manage**.

Example config:
// options: auto, manual (with command)
database_cleanupmode: auto
database_cleanupdays: 200
// options: load, unload
database_cleanupon: unload

**Comment by dumptruckman** [comment] 2017-06-09 18:56
Duplicate of #171.

**Closed by dumptruckman** 2017-06-09 18:56 UTC
Labels: Duplicate
