### ISSUE TITLE
Inventories Disappear when teleporting different worlds.

### ISSUE THREAD

**Issue by DeadIntermediate** [Multiverse/Multiverse-Inventories#130] opened 2013-01-19 14:07 UTC
I think there a bug or something that when a player go to a world (Hunger Games, Skyblock, Creative, Etc,) and stays in that world, let say from 5 minutes or more or something, and then come back the world previous (Lets say Spawn world, Survival, Etc,) Their inventory they first had would disappear. which at most time, I would have to replace all of the players items when this happens and it does get annoying after awhile. I hope you guys can fix this.

**Comment by dumptruckman** [comment] 2017-06-07 19:18
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 19:18 UTC
Labels: Assistance, Bug, Need More Information, Old - Open new issue if desired, Unconfirmed
