### ISSUE TITLE
Inventory swap between worlds

### ISSUE THREAD

**Issue by Chiekurins** [Multiverse/Multiverse-Inventories#127] opened 2013-01-09 16:12 UTC
A bug when you repeatably enter and re-enter portal you can swap your inventories, for example, you have 2 worlds, creative and survival, with this bug you can swap inventories, so the one used to be for survival is now for creative world, and vice versa. this way its possible to bug items.
using multiverse core, portals.

**Comment by dumptruckman** [comment] 2017-06-07 20:19
Probably duplicate of #161.

**Closed by dumptruckman** 2017-06-07 20:19 UTC
