### ISSUE TITLE
Error while building configuration map.

### ISSUE THREAD

**Issue by Wladislav** [Multiverse/Multiverse-Inventories#140] opened 2013-02-15 06:33 UTC
2013-02-15 07:04:13 [WARNING] [Multiverse-Inventories] Error while building configuration map.
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:528)
    at org.bukkit.craftbukkit.v1_4_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:512)
    at org.bukkit.craftbukkit.v1_4_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:498)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMap(JsonConfiguration.java:55)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMap(JsonConfiguration.java:56)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMap(JsonConfiguration.java:46)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMap(JsonConfiguration.java:46)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.saveToString(JsonConfiguration.java:32)
    at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.save(EncodedJsonConfiguration.java:30)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:243)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:30)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:209)

**Comment by dumptruckman** [comment] 2017-06-07 18:15
Probably duplicate of #266

**Closed by dumptruckman** 2017-06-07 18:15 UTC
Labels: Duplicate
