### ISSUE TITLE
Fixed/Pre-set Inventory

### ISSUE THREAD

**Issue by nebkat** [Multiverse/Multiverse-Inventories#96] opened 2012-10-20 14:09 UTC
I have an "arrow fight" world on my server and I would like every player to be given a certain inventory (1 bow, 32 arrows) on joining (or spawning in) the world. Would it be possible to have fixed inventories? If not a fixed inventory, at least a pre-set inventory that a player gets on first join to a world (e.g. basic tools on survival).

**Comment by dumptruckman** [comment] 2017-06-08 13:08
Duplicate of #212

**Closed by dumptruckman** 2017-06-08 13:08 UTC
