### ISSUE TITLE
Inventories switching worlds, wiping correct inventory

### ISSUE THREAD

**Issue by GaryQian** [Multiverse/Multiverse-Inventories#79] opened 2012-08-14 20:26 UTC
Recently, I have been getting reports of people glitching their Creative inventories into the survival world. After questioning, I have determined the cause to be from disconnection from the server (due to lag, bad internet, etc) wile switching worlds.

The player will try and use a method to switch worlds (portals, teleports, homes, etc) and if they drop their connection, their inventory from the world they set off from will replace the inv of the destination world when they log back in.

**Comment by dumptruckman** [comment] 2017-06-08 13:44
Probably duplicate of #161

**Closed by dumptruckman** 2017-06-08 13:44 UTC
