### ISSUE TITLE
World inventories swapping/disappearing.

### ISSUE THREAD

**Issue by Beaupedia** [Multiverse/Multiverse-Inventories#141] opened 2013-02-22 06:55 UTC
I have several players now who are losing their survival world inventories when coming back from a creative world. The creative world inventory is coming to survival, resulting in a difficult loss of their survival inventories.

11:52:54 PM
 CONSOLE:
[SEVERE] Cannot load plugins/Multiverse-Inventories/worlds/world/greencookieicing.json
11:52:54 PM
 CONSOLE:
JSON detected.
11:52:54 PM
 CONSOLE:
[SEVERE] Cannot load plugins/Multiverse-Inventories/worlds/world/greencookieicing.json
11:52:54 PM
 CONSOLE:
JSON detected.
11:52:54 PM
 CONSOLE:
[SEVERE] Cannot load plugins/Multiverse-Inventories/groups/survival/greencookieicing.json
11:52:54 PM
 CONSOLE:
JSON detected.
11:52:54 PM
 CONSOLE:
[INFO] greencookieicing was slain by Enderman
11:52:54 PM
 CONSOLE:
[SEVERE] Cannot load plugins/Multiverse-Inventories/groups/survival/greencookieicing.json
11:52:54 PM
 CONSOLE:
JSON detected.

**Comment by dumptruckman** [comment] 2017-06-07 18:14
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 18:14 UTC
Labels: Bug, Need More Information, Old - Open new issue if desired, Unconfirmed
