### ISSUE TITLE
Crash when TP

### ISSUE THREAD

**Issue by skulltraill** [Multiverse/Multiverse-Inventories#258] opened 2015-01-14 17:47 UTC
Hi.
Plugins: !(http://i.imgur.com/rW0f2nC.png?1)
MV ver: http://pastie.org/private/stmk600a9hkgeknpu8nmaw#19
Server log with crash report (gonna have to scroll down quite a bit) (line 1027): http://pastebin.com/QCeL4eaP

Issue: Whenever I tp using ANY command to a different world, server crashes. The whole server crashes.  Only I affect this, it doesn't happen to other players. I've cleared my inventory and it still happens. Deleted all the user data and it still happens. I don't know why.

Any help would really be appreciated. Thank you.

**Comment by Trojaner25** [comment] 2015-02-10 19:30
Caused by: <b>java.lang.OutOfMemoryError: Java heap space</b>
How much RAM did you assign to the server?

**Comment by dumptruckman** [comment] 2017-06-07 13:02
Yeah.. Appears to be due to running out of memory. It seems only coincidental that MV-Inventories was in the middle of loading that your server crashed.

**Closed by dumptruckman** 2017-06-07 13:02 UTC
