### ISSUE TITLE
[Critical Bug] Creative and Multiverse-Inventories

### ISSUE THREAD

**Issue by ArtificialTruth** [Multiverse/Multiverse-Inventories#187] opened 2013-07-02 22:51 UTC
Yea this is pretty bad.
If you go to a creative world, and warp to a survival world (no bungee) and QUICKLY open your inventory you have the items from creative. This happens most of the times, and sometimes the items will only appear for a second.

**Comment by dumptruckman** [comment] 2017-06-07 16:38
Duplicate of #161

**Closed by dumptruckman** 2017-06-07 16:38 UTC
