### ISSUE TITLE
Conversion from PerWorldInventory format inventories to Multiverse-Inventories

### ISSUE THREAD

**Issue by VL4DST3R** [Multiverse/Multiverse-Inventories#550] opened 2024-07-16 15:02 UTC
### Feature request

**Feature description**
Would it be possible for a conversion process (be it inside the plugin itself or an external tool) to allow people like me who use PerWorldInventory for inventory management to migrate to Multiverse-Inventories?

Both inventory files are mostly similar, both `.json`, albeit with different names for some sections, with only the file/folder structure differing more noticeably, where PerWorldInventory groups inventories by UUID folders, with the actual inventories inside named after the map and gamemode, e.g.:
`PerWorldInventory\data\8747f9a1-a733-33c5-b930-94153c44b883\hub_creative.json"`
I can provide examples for said player files or anything else that may be of use.

**How the feature is useful**
The plugin we come from is very old and seemingly abandoned, and seems to act in odd ways the further minecraft updates. I would love to switch to something more modern and better maintained like Multiverse Inventories but doing so as it currently stands would mean losing hundreds of character inventories over a few dozen maps that we had over many years.

**Comment by zax71** [comment] 2024-07-17 12:27
duplicate of #497

**Comment by zax71** [comment] 2024-07-17 12:27
duplicate of #497

**Closed by zax71** 2024-07-17 12:27 UTC
Labels: Type: Idea
