### ISSUE TITLE
Major Issue: Creative inventory able to taken to survival. Ruins economies and allows spawn egg mayhem.

### ISSUE THREAD

**Issue by Beaupedia** [Multiverse/Multiverse-Inventories#227] opened 2014-03-10 01:59 UTC
I've been informed by a player on my server that there's a glitch with Multiverse-Inventories wherein players can bring infinite resources from one world into the other, circumventing Multiverse-Inventories' efforts to keep the two worlds' inventories separate.

I've tested this and can confirm that it can be reproduced, the technique is a little tricky to master but it works every time once you get it right.

Essentially it's just a matter of timing:

1) go into the Creative Mode world

2) Load up your personal inventory with emerald blocks, spawn eggs, and all sorts of other goodies that completely throw off the economy and game-play in the Survival Mode world

3) Warp, teleport, or use a Multiverse Portal to move into the Survival Mode world. Just as the world is changing over, hit the 'E' key to bring up your inventory GUI window.

Voila! You now have your full personal inventory from the Creative World. Now you can spend those emeralds, spawn those creepers, and generally run amok in the Survival World.

This is NOT an Essentials specific issue. We have had this happen with Essentials, AdminCmd, and CommandBook.

**Comment by dumptruckman** [comment] 2017-06-07 14:07
Duplicate of #161

**Closed by dumptruckman** 2017-06-07 14:07 UTC
