### ISSUE TITLE
Big Problem Here.

### ISSUE THREAD

**Issue by SirMangler** [Multiverse/Multiverse-Inventories#166] opened 2013-04-23 18:25 UTC
I have a server with a hub and creative world and survival world, all using multiverse!

But, Survival world. How will I make it so you can enter the nether and end without losing items, please note if you help me on this that the main problem is some one could pick diamonds up from buildings in the hub, then go to the nether then back to survival and get free diamonds, same with creative. 

Thanks for reading, I really need help.

Minecraft Username: catty610

Server Ip: mc.teapot.im

**Comment by dumptruckman** [comment] 2017-06-07 17:10
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 17:10 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired, Shares
