### ISSUE TITLE
Resets Modular Power Suits / Applied Energistics

### ISSUE THREAD

**Issue by Nightreaver** [Multiverse/Multiverse-Inventories#191] opened 2013-07-22 22:02 UTC
I entered a world with separate inventory and had a modular power suit with lots of stuff on - when i entered it the new dim. everything was correctly removed.

But when i came back to the old and i get my MPS back it was completely resetted, no more modules installed and so on, so complete process there is lost.

Same with ME Remote Console, you get it back, but its empty and its unlinked

used 
Multiverse-Inventories-2.5.jar - build 357 
ModularPowersuits-0.7.0-534.jar
appeng-rv11-e-mc15x.zip

**Comment by dumptruckman** [comment] 2017-06-07 16:33
Probably a duplicate of #270.

**Closed by dumptruckman** 2017-06-07 16:33 UTC
