### ISSUE TITLE
1.9 Armor Problems

### ISSUE THREAD

**Issue by MatteCarra** [Multiverse/Multiverse-Inventories#286] opened 2016-03-07 12:17 UTC
I have this problem: http://pastebin.com/maDnzP4Y
I have updated spigot this morning. Now I am 4 versions behind

**Comment by matcracker** [comment] 2016-04-15 18:04
Because in 1.9 there are new slots, left hand and shield.

**Comment by dumptruckman** [comment] 2017-06-07 03:08
Closing as duplicate of #296.

**Closed by dumptruckman** 2017-06-07 03:08 UTC
Labels: Duplicate
