### ISSUE TITLE
Players losing inventory

### ISSUE THREAD

**Issue by Genocore** [Multiverse/Multiverse-Inventories#313] opened 2017-06-22 01:44 UTC
I run a semi vanilla survival server using spigot/paper. Recently updated to 1.12. I have a minigame world and a creative world with multiverse.
If a player spends a long time (somewhere over 1h+) in creative apart from the main survival world they lose their survival inventory when going back into the main world. 

Here is also a log of my console if it helps. No idea if related or not. http://prntscr.com/fmnti9

On a related issue i have a post from another player on friends server if it helps you any. http://prntscr.com/fmnsiy

If you need more info i shall try my best to help out.

Lastly thank you for an awesome plugin!! and updates. Free as well. 
Thanks.

**Comment by dumptruckman** [comment] 2017-06-22 02:08
This is a duplicate of #265. It has been fixed in https://ci.onarandombox.com/job/Multiverse-Inventories/423/

**Closed by dumptruckman** 2017-06-22 02:08 UTC
