### ISSUE TITLE
Multi-world 1 shop

### ISSUE THREAD

**Issue by superw44** [Multiverse/Multiverse-Inventories#148] opened 2013-03-08 04:25 UTC
Alright, so I have 3 worlds, one that has spawn and the shop, a pvp world and a non pvp world. I want the 2 build worlds to have separate inventories. However, I still want players to be able to buy from the spawn shop and have the items go to whichever world they want. Is this possible? If not, what do you suggest I do.

**Comment by dumptruckman** [comment] 2017-06-07 18:09
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed** 2017-06-07 18:09 UTC
Labels: Assistance, Old - Open new issue if desired
