### ISSUE TITLE
SEVERE Could not pass event InventoryCloseEvent to Multiverse-Inventories

### ISSUE THREAD

**Issue by Abysinian** [Multiverse/Multiverse-Inventories#81] opened 2012-08-17 20:23 UTC
MV VERSION -P LINK: http://j.mp/OGORkD

Hi there,

Ever since I installed Multiverse on my server, whenever someone opens a chest or their inventory, the console gives this error:
ERROR: 

17.08 22:17:34 [Server] INFO ... 11 more
17.08 22:17:34 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
17.08 22:17:34 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source)
17.08 22:17:34 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
17.08 22:17:34 [Server] INFO at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
17.08 22:17:34 [Server] INFO at com.onarandombox.multiverseinventories.TemporaryEnderChestListener.inventoryClose(TemporaryEnderChestListener.java:77)
17.08 22:17:34 [Server] INFO Caused by: java.lang.NoSuchFieldError: ENDER_CHEST
17.08 22:17:34 [Server] INFO at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
17.08 22:17:34 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
17.08 22:17:34 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:579)
17.08 22:17:34 [Server] INFO at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
17.08 22:17:34 [Server] INFO at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:119)
17.08 22:17:34 [Server] INFO at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
17.08 22:17:34 [Server] INFO at net.minecraft.server.Packet101CloseWindow.handle(SourceFile:16)
17.08 22:17:34 [Server] INFO at net.minecraft.server.NetServerHandler.handleContainerClose(NetServerHandler.java:1071)
17.08 22:17:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
17.08 22:17:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
17.08 22:17:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
17.08 22:17:34 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
17.08 22:17:34 [Server] INFO org.bukkit.event.EventException
17.08 22:17:34 [Server] SEVERE Could not pass event InventoryCloseEvent to Multiverse-Inventories

It does it every single time anyone opens either their inventory or a chest and clogs up the console quite badly if the server is busy.

I'm running the latest version listed on your BukkitDev page (2.4-AB) and I have all the other Multiverse Plugins at their latest build too.

My server is running Tekkit 3.1.2

I apologise if you've covered this somewhere else but I couldn't find anything about it.

Thanks for your time/help.

Update: My Server Host contacted me about this error as it must have been flagged up on their system because it's happening so often.

STARTUP LOG:

18.08 15:18:56 [Server] Startup Done (6.586s)! For help, type "help" or "?"
18.08 15:18:56 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
18.08 15:18:56 [Server] INFO [EssentialsSpawn] Enabling EssentialsSpawn v2.9.2
18.08 15:18:56 [Server] INFO [Residence] Enabled! Version 2.6.5 by bekvon
18.08 15:18:56 [Server] SEVERE Plugin Residence is attempting to register event org/bukkit/event/player/AsyncPlayerChatEvent, which does not exist. Ignoring events registered in class com.bekvon.bukkit.residence.listeners.ResidencePlayerListener
18.08 15:18:56 [Server] INFO [Residence] Found WorldEdit
18.08 15:18:56 [Server] INFO [Residence] Successfully linked with Essentials Economy!
18.08 15:18:56 [Server] INFO [Residence] BOSEconomy NOT found!
18.08 15:18:56 [Server] INFO [Residence] Vault NOT found!
18.08 15:18:56 [Server] INFO [Residence] Scanning for economy systems...
18.08 15:18:56 [Multicraft] Skipped 120 lines due to rate limit (30/s)
18.08 15:18:55 [Server] INFO WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
18.08 15:18:55 [Server] INFO [PermissionsEx] v1.19.3 enabled
18.08 15:18:55 [Server] INFO [PermissionsEx] Superperms support enabled.
18.08 15:18:55 [Server] INFO [PermissionsEx] Enabling PermissionsEx v1.19.3
18.08 15:18:55 [Server] INFO [MultiVerse-NetherPortals] - Version 2.4-b530 Enabled - By Rigby and fernferret
18.08 15:18:55 [Server] INFO [Multiverse-NetherPortals] Enabling Multiverse-NetherPortals v2.4-b530
18.08 15:18:55 [Server] INFO [Multiverse-Inventories 2.5-b195] enabled.
18.08 15:18:55 [Server] INFO [Multiverse-Inventories] Enabling Multiverse-Inventories v2.5-b195
18.08 15:18:55 [Server] INFO WEPIF: Using the Bukkit Permissions API.
18.08 15:18:55 [Server] INFO [WorldEdit] Enabling WorldEdit v5.3
18.08 15:18:55 [Server] INFO [Votifier] Votifier enabled.
18.08 15:18:55 [Server] INFO [Votifier] Loaded vote listener: essEcoListener
18.08 15:18:55 [Server] INFO [Votifier] Loaded vote listener: ItemListener
18.08 15:18:55 [Server] INFO [Votifier] Enabling Votifier v1.8
18.08 15:18:55 [Server] INFO [Multiverse-Core] 6 - World(s) loaded.
18.08 15:18:54 [Server] INFO Preparing start region for level 5 (Seed: -5772778872049268660)
18.08 15:18:54 [Server] INFO Registering world nopvp_the_end, dimension 4, of providertype net.minecraft.server.WorldProviderTheEnd@6e6cd0e8(0) with Minecraft Forge
18.08 15:18:54 [Server] INFO [Multiverse-Core] Loading World & Settings - 'nopvp_the_end' - Env: THE_END - Type: NORMAL & seed: -5772778872049268660
18.08 15:18:54 [Server] INFO Preparing start region for level 4 (Seed: 4339018464377510921)
18.08 15:18:54 [Server] INFO Registering world NoPvP_Nether, dimension 3, of providertype net.minecraft.server.WorldProviderHell@4d50c322(0) with Minecraft Forge
18.08 15:18:54 [Server] INFO [Multiverse-Core] Loading World & Settings - 'NoPvP_Nether' - Env: NETHER - Type: NORMAL & seed: 4339018464377510921
18.08 15:18:53 [Server] INFO Preparing start region for level 3 (Seed: -6568155802017284539)
18.08 15:18:53 [Server] INFO Registering world nopvp, dimension 2, of providertype net.minecraft.server.WorldProviderNormal@cb604f5(0) with Minecraft Forge
18.08 15:18:53 [Server] INFO [Multiverse-Core] Loading World & Settings - 'nopvp' - Env: NORMAL - Type: NORMAL & seed: -6568155802017284539
18.08 15:18:53 [Server] INFO [Multiverse-Core] Loading World & Settings - 'world_nether' - Env: NETHER - Type: NORMAL & seed: 7354270821348208437
18.08 15:18:53 [Server] INFO [Multiverse-Core] Loading World & Settings - 'world_the_end' - Env: THE_END - Type: NORMAL & seed: 7354270821348208437
18.08 15:18:53 [Server] INFO [Multiverse-Core] Loading World & Settings - 'world' - Env: NORMAL - Type: NORMAL & seed: 7354270821348208437
18.08 15:18:53 [Server] INFO [AllPay] - Version 10.0 - hooked into Essentials Economy for Multiverse-Core v2.4-b527
18.08 15:18:53 [Server] INFO [Multiverse-Core] - Version 2.4-b527 (API v14) Enabled - By Rigby, fernferret, lithium3141 and main--
18.08 15:18:53 [Server] INFO [Multiverse-Core] Enabling Multiverse-Core v2.4-b527
18.08 15:18:53 [Server] INFO [Buycraft] Plugin has been successfully enabled.
18.08 15:18:53 [Server] INFO [Buycraft] Loaded 3 package(s) into the cache.
18.08 15:18:52 [Server] SEVERE Plugin Buycraft is attempting to register event org/bukkit/event/player/AsyncPlayerChatEvent, which does not exist. Ignoring events registered in class net.buycraft.PlayerListener
18.08 15:18:52 [Server] INFO [Buycraft] Enabling Buycraft v4.6
18.08 15:18:52 [Server] INFO For reference, the main world's spawn location is at X: -163.0 Y: 64.0 Z: 250.0
18.08 15:18:52 [Server] INFO [WorldBorder] [CONFIG] Border-checking timed task started.
18.08 15:18:52 [Server] INFO [WorldBorder] [CONFIG] Using round border, knockback of 1.0 blocks, and timer delay of 5.
18.08 15:18:52 [Server] INFO [WorldBorder] Enabling WorldBorder v1.5.4
18.08 15:18:51 [Server] INFO Preparing start region for level 2 (Seed: 7354270821348208437)
18.08 15:18:51 [Server] INFO Preparing spawn area: 52%
18.08 15:18:51 [Server] INFO Preparing start region for level 1 (Seed: 7354270821348208437)
18.08 15:18:50 [Server] INFO Preparing start region for level 0 (Seed: 7354270821348208437)
18.08 15:18:50 [Server] INFO Registering world world_nether, dimension -1, of providertype net.minecraft.server.WorldProviderHell@52cf14c4(0) with Minecraft Forge
18.08 15:18:50 [Server] INFO Registering world world_the_end, dimension 1, of providertype net.minecraft.server.WorldProviderTheEnd@3b474cb5(0) with Minecraft Forge
18.08 15:18:50 [Server] INFO Registering world world, dimension 0, of providertype net.minecraft.server.WorldProviderNormal@5c486c52(0) with Minecraft Forge
18.08 15:18:50 [Server] INFO Default game type: 0
18.08 15:18:50 [Server] INFO Preparing level "world"
18.08 15:18:50 [Multicraft] Skipped 122 lines due to rate limit (30/s)
18.08 15:18:49 [Server] INFO Loading mod_NetherOres vForgeMod
18.08 15:18:49 [Server] INFO [Multiverse-Core] Loading Multiverse-Core v2.4-b527
18.08 15:18:49 [Server] INFO Loading mod_BuildCraftFactory vForgeMod
18.08 15:18:49 [Server] INFO Loading mod_ImmibisCore vForgeMod
18.08 15:18:49 [Server] INFO [Buycraft] Loading Buycraft v4.6
18.08 15:18:49 [Server] INFO Loading mod_BuildCraftCore vForgeMod

**Comment by dumptruckman** [comment] 2017-06-08 13:43
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-08 13:43 UTC
Labels: Bug, Old - Open new issue if desired, Unconfirmed
