### ISSUE TITLE
Problem With XP

### ISSUE THREAD

**Issue by Teehee123123** [Multiverse/Multiverse-Inventories#192] opened 2013-08-03 19:33 UTC
Theres something wrong with XP Levels and Im losing players because of it, can I get assistance on fixing my issues with XP Sharing? When they switch worlds their XP disappears and when they go back to the previous world they were in the XP acts as if it was never there. And its crazy because the shares are all correct

**Comment by dumptruckman** [comment] 2017-06-07 16:32
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 16:32 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired
