### ISSUE TITLE
Bed respawns deleting

### ISSUE THREAD

**Issue by kbryant** [Multiverse/Multiverse-Inventories#137] opened 2013-02-09 03:51 UTC
Multiverse-Inventories v2.5-b335
Essentials vPre2.10.1.4
CraftBukkit v1.4.7-R1.1-SNAPSHOT

Essentials has a feature where you can set a "/home bed". I believe this is using the bed's respawn point as a home.

With this set in my MV-Inventories config: "use_game_mode_profiles: true"
Whenever a Player changes gamemodes, his bed respawn is deleted. "/home bed" is erased and the player has to re-set it.

**Comment by xtechgamer735** [comment] 2017-07-09 13:23
Unable to reproduce this

**Comment by dumptruckman** [comment] 2017-07-09 14:00
Closing since this is old and it may be fixed now. Open a new ticket if you have this problem with the latest dev builds.

**Closed by dumptruckman** 2017-07-09 14:00 UTC
Labels: Bug, Unconfirmed
