### ISSUE TITLE
Multiverse Inventories Broke after newest paper build.

### ISSUE THREAD

**Issue by pupshadow** [Multiverse/Multiverse-Inventories#482] opened 2022-01-10 07:01 UTC
### Information

* **Server version:** 
This server is running Paper version git-Paper-144 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 87d8ef9)

* **Full output of `/mv version -p`:** 
https://paste.gg/p/anonymous/ccbbbb6342544d8690760b4141fe3c83

* **Server log:** 
https://gist.github.com/pupshadow/6b7a52f0dbd2409b937dec0ed3327abf

### Details
I was **`<able>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Newest Paper Build Broke MVI.

**Steps to reproduce**  
Just Start Your Server Up.

**Expected behavior**  
To Work Properly.

**Log of error itself**  
(https://pastebin.com/g9m57Rha)

**Comment by benwoo1110** [comment] 2022-01-10 07:02
Duplicate of #480, likely an issue with one of the paper's dependencies that parses YAML file.

**Closed by benwoo1110** 2022-01-10 07:02 UTC
Labels: Bug: Unconfirmed
