### ISSUE TITLE
No group with this name when using /mvinv group

### ISSUE THREAD

**Issue by blakfyr999** [Multiverse/Multiverse-Inventories#190] opened 2013-07-15 09:02 UTC
I literally think this screenshot tells it all. 

It's also the only information I have on the issue. I'm trying to edit my existing groups (to add worlds to them- nether and end worlds I just created for PVP and Creative)

http://puu.sh/3DjKO.jpg

**Comment by dumptruckman** [comment] 2017-06-07 16:34
Duplicate of #223.

**Closed by dumptruckman** 2017-06-07 16:34 UTC
Labels: Duplicate
