### ISSUE TITLE
Extra characters appending to start of colored-lorenamed items

### ISSUE THREAD

**Issue by Steelsouls** [Multiverse/Multiverse-Inventories#146] opened 2013-03-01 22:02 UTC
Expected Behavior:
Use /mvtp to travel between worlds in separate groups. All items reload into inventory as-is.

What happens:
Items with colored names have symbols appended to start of name. This only happens on inventory load, not when joining/leaving server. The more times the player transfers between worlds, the more characters get added to the name.

Images of issue:
http://imgur.com/a/kvCOJ#3

Related info:
OtherDrops - Plugin that is spawning the items. Example item spawn
    /odd DIAMOND@!~&6Magic Gem   (Diamond with orange name Magic Gem)
        Plugin converts & to § before creating the item

Versions:
Bukkit 1.4.7R1.0
MV-Core 2.5-b656
MV-Inventories 2.5-b332 (persists in 335)
MV-Portals 2.5-b674
OtherDrops 2.8b.89 (persists through versions)

**Comment by dumptruckman** [comment] 2017-06-07 18:11
Duplicate of #266

**Closed by dumptruckman** 2017-06-07 18:11 UTC
