### ISSUE TITLE
Multiverse /back issue

### ISSUE THREAD

**Issue by SirMangler** [Multiverse/Multiverse-Inventories#194] opened 2013-08-25 11:42 UTC
When a player goes into the nether, changes around there items a bit, then do /back they have there original items back.

**Comment by dumptruckman** [comment] 2017-06-07 16:31
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 16:31 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired
