### ISSUE TITLE
Bug during the change of inventory

### ISSUE THREAD

**Issue by bvilliot** [Multiverse/Multiverse-Inventories#207] opened 2013-12-15 10:13 UTC
I would first of all like to thank you for these plugins, which are very complete, which do not almost contain bugs (in 1.5.2) and which work very well. Thank you :)

I just have a small bug at the moment. Indeed I possess two worlds: one in survival, and an other one in creative. Multivers inventory works well, it changes inventory during the teleportation between both worlds. But if during the teleportation, a player spams the touch to open his inventory, at the end he will have his two inventories which will have merged (the items of the world of departure replacing the items of the world of arrived positioned on the same place in the inventory).
Do you know if there is a way to by-pass the problem?

Thank you very much

**Comment by dumptruckman** [comment] 2017-06-07 14:55
Duplicate of #161

**Closed by dumptruckman** 2017-06-07 14:55 UTC
Labels: Duplicate
