### ISSUE TITLE
Inventory is reverting to an old inventory on teleport across worlds

### ISSUE THREAD

**Issue by ty2u** [Multiverse/Multiverse-Inventories#155] opened 2013-03-19 01:27 UTC
Hello,

Getting this error:

Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v2.5-b335: http://pastebin.com/MDTbebLb

This server is running CraftBukkit version git-Spigot-607 (MC: 1.4.7) (Implementing API version 1.4.7-R1.1-SNAPSHOT)

In this case they were teleporting from a creative world into a survival world.

I think it's because there are both yml and json files in the worlds folder for MI and it must just fall back to using the yml for some reason. I'm not sure if I should delete those or what. I think if they are unneeded the plugin should delete them.

Thanks!

**Comment by dumptruckman** [comment] 2017-06-07 17:56
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 17:56 UTC
Labels: Bug, Need More Information, Old - Open new issue if desired, Unconfirmed, Unrelated
