### ISSUE TITLE
How do i make so a inventory is kept from a same world?

### ISSUE THREAD

**Issue by lpb007** [Multiverse/Multiverse-Inventories#169] opened 2013-05-05 18:43 UTC
Help me please!

**Comment by dumptruckman** [comment] 2017-06-07 17:07
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 17:07 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired, Shares
