### ISSUE TITLE
Problem with inventory when changing main world

### ISSUE THREAD

**Issue by eXecU7i0neR** [Multiverse/Multiverse-Inventories#142] opened 2013-02-23 22:47 UTC
I have old world (i will call it "world") that i want to delete, that is main world. All inventories are connected to this world, and are shared with all other worlds, except creative world. Now i have to set new world (i will call it "newworld") as main world in server.properties, but when i do that, all inventories are lost.
I tried to copy all json and yml files from "world" folder to "newworld" folder, but i always get new inventory. I spawned in that new inventory 2 stacks od stone, and i get that inventory, what ever i do.

I guess, there is a way to transfer this in to new world, they are sharing it already, but i don'tknow how. Can someone help me?

Thanx :)

**Comment by dumptruckman** [comment] 2017-06-07 18:13
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 18:13 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired
