### ISSUE TITLE
Custom Heads

### ISSUE THREAD

**Issue by HeadlessJoey** [Multiverse/Multiverse-Inventories#276] opened 2015-12-26 12:54 UTC
Hi,

Lately I have been using a website called http://heads.freshcoal.com/ this website generates custom player heads. The thing is that your inventory system isn't able to store these custom heads because they aren't exactly player heads.
I would love it if you could find a way to store these kind of heads aswell.

Example of a generated head command:
/give @p skull 1 3 {display:{Name:"Bread"},SkullOwner:{Id:"a75e3f60-2242-4429-8ece-bcde7753b064",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjM0ODdkNDU3ZjkwNjJkNzg3YTNlNmNlMWM0NjY0YmY3NDAyZWM2N2RkMTExMjU2ZjE5YjM4Y2U0ZjY3MCJ9fX0="}]}}}

Site basics:
It's a head generator and a online database for these heads. Basically the generator creates a snapshot of the head of the player at that specific moment. You can then change your skin to redo the process, the previously generated heads will not change.

**Comment by dumptruckman** [comment] 2017-06-07 03:40
You may not care anymore but if I do end up resurrecting this plugin I have a feeling I will get around to making this work. I am probably going to switch the inventory data *back* to YAML since Bukkit has much better item serialization now than it did when this plugin was originally made.

**Comment by dumptruckman** [comment] 2017-06-07 05:06
Duplicate of #266.

**Closed by dumptruckman** 2017-06-07 05:06 UTC
Labels: Duplicate
