### ISSUE TITLE
Colored Items Bug

### ISSUE THREAD

**Issue by Jhpirate** [Multiverse/Multiverse-Inventories#224] opened 2014-02-19 01:35 UTC
There's a bug that I think this plugin is the cause, but when you have a formatted item lore or name, go out of the world with nobody but you in it, return, it starts filling up with strange characters every time, this also happens to books. I'm not sure if this plugin is the cause but I'm concerned about this bug. The problem is I think the encoding of the player.json files are stored in ANSI when they should be in UTF-8. Can you fix this because its really affecting my colored items and kits.

The following is the symbol that start to appear:
![help](https://f.cloud.github.com/assets/4596344/2202567/25aa8f08-9906-11e3-8c40-8e114c51a788.PNG)

**Comment by dumptruckman** [comment] 2017-06-07 14:09
Duplicate of #270

**Closed by dumptruckman** 2017-06-07 14:09 UTC
