### ISSUE TITLE
Inventories got switched

### ISSUE THREAD

**Issue by y0ur0wned** [Multiverse/Multiverse-Inventories#196] opened 2013-09-01 09:45 UTC
On my server we have different worlds running with multiverse.

We have a skyblock world and a main world (which is acting like a lobby)
Since today we got a problem. 
The inventories of the Skyblock world have switched with the inventories of the main world.
Is there a way to switch them back? So the people on skyblock world get the right inventories back?

I have been searching the internet for people with a problem just like this and i couldn't find one so you guys are my last hope.

**Comment by dumptruckman** [comment] 2017-06-07 16:29
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 16:29 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired
