### ISSUE TITLE
2 Worlds Sharing XP? Bug?

### ISSUE THREAD

**Issue by greaperc4** [Multiverse/Multiverse-Inventories#144] opened 2013-02-25 17:59 UTC
Well, i have more worlds, en 2 worlds have xp shared: i tried experience on shared xp and total_xp non of them works
when someone is switching to the 2nd world he stays at the XP he has in the first world
if i give him extra xp in the 2nd world and he switches back to the 1st world he will lose the XP i gave to him.
Why is This and could this be Fixed!??

Oops sorry for Posting 2 topics.. i thought i could make it in the bug section but there isnt one :$

thanks, Regards greaperc4

**Comment by dumptruckman** [comment] 2017-06-07 18:12
Duplicate of #143

**Closed by dumptruckman** 2017-06-07 18:12 UTC
Labels: Duplicate
