### ISSUE TITLE
Inventories seperate in creative and survival

### ISSUE THREAD

**Issue by jthom44** [Multiverse/Multiverse-Inventories#163] opened 2013-04-12 11:16 UTC
i want them to be the same they are for all my other worlds however for my walls world it seems that the creative is different from the survival and adventure, idk how to fix it and i need it fast

**Comment by dumptruckman** [comment] 2017-06-07 17:12
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed** 2017-06-07 17:12 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired, Shares
