### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by XboxFest** [Multiverse/Multiverse-Inventories#181] opened 2013-06-18 07:11 UTC
This is my world list below.
FactionPvP
Herobrine
Skyrim
Skyrim_nether
Skyrim_the_end
Spawn
Spawn_nether
Spawn_the_end
world_herobrineai_graveyard

What I have done:
1. Delete the default group
2. Create group called "factionpvp" and added the following worlds: FactionPvP, Spawn_nether, Spawn_the_end and made them share all.

This was to test if it works

Was in the world factionpvp and teleported to Spawn_the_end. Didn't keep my stuff.

HELP?!

**Comment by dumptruckman** [comment] 2017-06-07 16:42
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 16:42 UTC
Labels: Assistance, Old - Open new issue if desired, Shares
