### ISSUE TITLE
Add share for golden hearts from golden apples

### ISSUE THREAD

**Issue by gustebeast** [Multiverse/Multiverse-Inventories#228] opened 2014-03-23 16:31 UTC
If a player eats a golden apple and gets the bonus hearts, it will not reset upon moving to a world separated by multiverse-inventories.

**Comment by dumptruckman** [comment] 2017-07-08 13:40
Okay, this is a potion effect. Need to investigate why it's not being transferred. Probably related to #185.

**Comment by xtechgamer735** [comment] 2017-07-09 14:02
Unable to reproduce this - golden hearts are shared or restricted where set.

**Comment by dumptruckman** [comment] 2017-07-09 14:10
Closing since this is old and it may be fixed now. Open a new ticket if you have this problem with the latest dev builds.

**Closed by dumptruckman** 2017-07-09 14:10 UTC
Labels: Bug, Unconfirmed
