### ISSUE TITLE
Whitelist Items

### ISSUE THREAD

**Issue by DBawesomeness17** [Multiverse/Multiverse-Inventories#217] opened 2014-01-16 01:35 UTC
I  think it would be very beneficial if you could whitelist certain items, like a compass or something that you carry to different worlds but can still use. so you would do a command like /mvinv whitelist (Item help in hand), I think that would make this plugin even that much greater. if this could happen that would be very cool!

**Comment by dumptruckman** [comment] 2017-06-07 14:18
Duplicate of #290.

**Closed by dumptruckman** 2017-06-07 14:18 UTC
