### ISSUE TITLE
Custom items get all screwed up when changing worlds

### ISSUE THREAD

**Issue by xtomyserrax** [Multiverse/Multiverse-Inventories#261] opened 2015-01-30 08:03 UTC
Hey! Could you possibly add compability with GuiShopManager plugin? ( http://dev.bukkit.org/bukkit-plugins/guishopmanager/ )

Because when i change the world with Multiverse-Inventories the item gets like this: http://imgur.com/0uzIT3i

Thanks!

**Comment by hockeymikey** [comment] 2015-02-08 08:56
Make sure the server is using Unicode for encoding, that's the issue.

**Comment by dumptruckman** [comment] 2017-06-07 05:10
Duplicate of #270

**Closed by dumptruckman** 2017-06-07 05:10 UTC
