### ISSUE TITLE
Server crashes with java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by petwall** [Multiverse/Multiverse-Inventories#149] opened 2013-03-11 22:22 UTC
I get infrequent server crashes with the following stack trace;

```
2013-03-11 17:56:39 [SEVERE] Exception in thread "MV-Inv Profile Write Thread" 
2013-03-11 17:56:39 [SEVERE] java.lang.OutOfMemoryError: Requested array size exceeds VM limit
2013-03-11 17:56:39 [SEVERE]    at java.util.Arrays.copyOf(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at java.lang.AbstractStringBuilder.append(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at java.lang.StringBuffer.append(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONValue.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONValue.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONValue.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONValue.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONValue.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONObject.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at org.json.simple.JSONValue.toJSONString(Unknown Source)
2013-03-11 17:56:39 [SEVERE]    at com.onarandombox.multiverseinventories.util.JsonConfiguration.saveToString(JsonConfiguration.java:32)
2013-03-11 17:56:39 [SEVERE]    at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.save(EncodedJsonConfiguration.java:30)
2013-03-11 17:56:39 [SEVERE]    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:243)
2013-03-11 17:56:39 [SEVERE]    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:30)
2013-03-11 17:56:39 [SEVERE]    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:209)
```

I usually see a prior entry with;

```
2013-03-11 17:55:59 [INFO] USERNAME lost connection: disconnect.endOfStream
2013-03-11 17:55:59 [WARNING] Failed to save player data for USERNAME
```

There is always a stale USERNAME.tmp file in the bukkit/WORLNAME/players/ folder.

I see no strange things with extremely big files, so I suspect something else breaks on the failed save exception that gives the first warning (seem to be the same pattern all the time).

The server has _plenty_ of memory available:

```
java -Xms3024M -Xmx14072M -jar craftbukkit-1.4.7-R1.0.jar
```

So I guess some string length in the callstack is just bogus and render the bug.

Running on Windows 7 x64.

**Comment by dumptruckman** [comment] 2017-06-07 18:08
Probably duplicate of #208

**Closed by dumptruckman** 2017-06-07 18:08 UTC
