### ISSUE TITLE
X group does not exist when trying to edit it

### ISSUE THREAD

**Issue by Nadoomi** [Multiverse/Multiverse-Inventories#235] opened 2014-05-08 21:35 UTC
![image](https://cloud.githubusercontent.com/assets/7528058/2921797/a99e9b30-d6f8-11e3-87c8-6ca1df3411e0.png)

**Comment by dumptruckman** [comment] 2017-06-07 14:10
Duplicate of #223.

**Closed by dumptruckman** 2017-06-07 14:10 UTC
Labels: Duplicate
