### ISSUE TITLE
Could not pass event PlayerDeathEvent to Multiverse-Inventories v2.5-b335

### ISSUE THREAD

**Issue by Citaborg** [Multiverse/Multiverse-Inventories#129] opened 2013-01-15 18:54 UTC
This one happens regularly(se trace below) - and Down the stack it says Java heap out of mem. GC a second later gives:

19:49:57 [INFO] Uptime: 44 minutes 14 seconds
19:49:57 [INFO] Current TPS = 20.0
19:49:57 [INFO] Maximum memory: 4á551 MB
19:49:57 [INFO] Allocated memory: 4á255 MB
19:49:57 [INFO] Free memory: 1á377 MB

--- stacktrace / log -------

2013-01-15 19:49:49 [SEVERE] Could not pass event PlayerDeathEvent to Multiverse-Inventories v2.5-b335
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:332)
    at net.minecraft.server.v1_4_6.EntityPlayer.die(EntityPlayer.java:256)
    at net.minecraft.server.v1_4_6.EntityLiving.damageEntity(EntityLiving.java:758)
    at net.minecraft.server.v1_4_6.EntityHuman.damageEntity(EntityHuman.java:617)
    at net.minecraft.server.v1_4_6.EntityPlayer.damageEntity(EntityPlayer.java:309)
    at net.minecraft.server.v1_4_6.Entity.y(Entity.java:324)
    at net.minecraft.server.v1_4_6.EntityLiving.y(EntityLiving.java:310)
    at net.minecraft.server.v1_4_6.Entity.j_(Entity.java:237)
    at net.minecraft.server.v1_4_6.EntityLiving.j_(EntityLiving.java:508)
    at net.minecraft.server.v1_4_6.EntityHuman.j_(EntityHuman.java:156)
    at net.minecraft.server.v1_4_6.EntityPlayer.g(EntityPlayer.java:194)
    at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:351)
    at net.minecraft.server.v1_4_6.Packet10Flying.handle(SourceFile:136)
    at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
    at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
    at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
    at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:585)
    at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
    at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:481)
    at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:416)
    at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2367)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:587)
    at java.lang.StringBuilder.append(StringBuilder.java:214)
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:132)
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(JsonConfiguration.java:184)
    at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.<init>(EncodedJsonConfiguration.java:20)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:77)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:269)
    at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
    at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87)
    at com.onarandombox.multiverseinventories.InventoriesListener.playerDeath(InventoriesListener.java:234)
    at sun.reflect.GeneratedMethodAccessor308.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:332)
    at net.minecraft.server.v1_4_6.EntityPlayer.die(EntityPlayer.java:256)
    at net.minecraft.server.v1_4_6.EntityLiving.damageEntity(EntityLiving.java:758)
    at net.minecraft.server.v1_4_6.EntityHuman.damageEntity(EntityHuman.java:617)
    at net.minecraft.server.v1_4_6.EntityPlayer.damageEntity(EntityPlayer.java:309)
    at net.minecraft.server.v1_4_6.Entity.y(Entity.java:324)
    at net.minecraft.server.v1_4_6.EntityLiving.y(EntityLiving.java:310)
    at net.minecraft.server.v1_4_6.Entity.j_(Entity.java:237)
    at net.minecraft.server.v1_4_6.EntityLiving.j_(EntityLiving.java:508)
    at net.minecraft.server.v1_4_6.EntityHuman.j_(EntityHuman.java:156)
    at net.minecraft.server.v1_4_6.EntityPlayer.g(EntityPlayer.java:194)

**Comment by dumptruckman** [comment] 2017-06-07 20:14
Probably duplicate of #208

**Closed by dumptruckman** 2017-06-07 20:14 UTC
