### ISSUE TITLE
How to get nether & mainworld to share inventories

### ISSUE THREAD

**Issue by FlawlessSin** [Multiverse/Multiverse-Inventories#145] opened 2013-02-26 21:45 UTC
So, sorry for the noobish question, but i just can't figure this out, I've added the Groups to the config, and the Mainworld, Nether, and End world, and put shares to -all, however the inventories are STILL being reset when switching worlds.

**Comment by dumptruckman** [comment] 2017-06-07 18:12
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 18:12 UTC
Labels: Assistance, Need More Information, Old - Open new issue if desired
