### ISSUE TITLE
Error while building configuration map

### ISSUE THREAD

**Issue by paulj1x** [Multiverse/Multiverse-Inventories#168] opened 2013-05-05 17:24 UTC
Getting the following warning every 1 to 3 minutes, and then occasionally the following severe errors.

Multiverse-Core v2.5-b665
Multiverse-Portals  v2.5-b685
Multiverse-SignPortal   v2.5-b651
Multiverse-Inventories  2.5-b350
CraftBukkit version git-Spigot-844 (MC: 1.5.2) (Implementing API version 1.5.2-R0.2-SNAPSHOT)

[Multiverse-Inventories] Error while building configuration map.
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:539)
    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:523)
    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:509)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMap(JsonConfiguration.java:55)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMap(JsonConfiguration.java:56)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMap(JsonConfiguration.java:46)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.buildMap(JsonConfiguration.java:46)
    at com.onarandombox.multiverseinventories.util.JsonConfiguration.saveToString(JsonConfiguration.java:32)
    at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.save(EncodedJsonConfiguration.java:30)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:243)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:30)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:209)
2013-05-05 02:32:14 [SEVERE] java.lang.NullPointerException
2013-05-05 02:32:14 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:539)
2013-05-05 02:32:14 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:523)
2013-05-05 02:32:14 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:509)
2013-05-05 02:32:14 [SEVERE]    at net.coreprotect.database.Logger.container_logger(Logger.java:391)
2013-05-05 02:32:14 [SEVERE]    at net.coreprotect.database.Logger.log_container(Logger.java:318)
2013-05-05 02:32:14 [SEVERE]    at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:222)
2013-05-05 02:32:14 [SEVERE]    at net.coreprotect.consumer.Process.processConsumer(Process.java:83)
2013-05-05 02:32:14 [SEVERE]    at net.coreprotect.consumer.Consumer.run(Consumer.java:49)
2013-05-05 02:32:14 [SEVERE]    at java.lang.Thread.run(Unknown Source)
2013-05-05 02:32:16 [SEVERE] java.lang.NullPointerException
2013-05-05 02:32:16 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:539)
2013-05-05 02:32:16 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:523)
2013-05-05 02:32:16 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:509)
2013-05-05 02:32:16 [SEVERE]    at net.coreprotect.database.Logger.container_logger(Logger.java:391)
2013-05-05 02:32:16 [SEVERE]    at net.coreprotect.database.Logger.log_container(Logger.java:317)
2013-05-05 02:32:16 [SEVERE]    at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:222)
2013-05-05 02:32:16 [SEVERE]    at net.coreprotect.consumer.Process.processConsumer(Process.java:83)
2013-05-05 02:32:16 [SEVERE]    at net.coreprotect.consumer.Consumer.run(Consumer.java:49)
2013-05-05 02:32:16 [SEVERE]    at java.lang.Thread.run(Unknown Source)

**Comment by Starmaster** [comment] 2015-10-07 03:05
same problem here!

**Comment by dumptruckman** [comment] 2017-06-07 17:08
Probable duplicate of #266

**Closed by dumptruckman** 2017-06-07 17:08 UTC
