### ISSUE TITLE
Endless resources

### ISSUE THREAD

**Issue by DramaKongen** [Multiverse/Multiverse-Inventories#184] opened 2013-06-26 10:41 UTC
I found out on my server that it is a bug in version 2.5-B335 of the Multiverse-Inventories where players can bring endless resources from one world to the other, immediately Multiverse-Inventories' efforts to keep the two worlds separate inventory.

I have tested this and can confirm that it can be reproduced, the technique is a little tricky to master, but it works every time when you get it right.

Essentially it's just a matter of timing:

1) Go into Creative Mode world

2) Add up the inventory with emerald blocks, monster eggs and all sorts of other goodies that completely throw off the economy and game-play in Survival Mode World

3) Warp, teleport, or use a Multiverse Portal to move into Survival Mode world. Just as the world is changing again, press "E" key to bring up the Inventory GUI window.

Voila! You now have your full inventory of Creative World. Now you can use these emeralds, spawn monsters, and generally running amok in the Survival World.

versions:

Bukkit: git-Bukkit-1.4.7-R1.0-94-g141dcf0-b2735jnks (MC: 1.5.1)
Multiverse-Core: 2.5-b641 (beta)
Multiverse-Inventories: 2.5-B335
Multiverse Portals: 2.4-AB
(even if the glitch works even with Multiverse Portals disabled, when users teleport or warp from one world to the other)

**Comment by dumptruckman** [comment] 2017-06-07 16:40
Duplicate of #161

**Closed by dumptruckman** 2017-06-07 16:40 UTC
Labels: Duplicate
