### ISSUE TITLE
Inventory and enderchest lost going from survival to creative

### ISSUE THREAD

**Issue by rnoa** [Multiverse/Multiverse-Inventories#201] opened 2013-10-30 07:50 UTC
Have had this issue for a long time and haven't been able to solve it. The players going from survival to creative world using multiverse portals lose all their entire  inventories and enderchest content which doesn't restore when they go back! The worlds are configured to no shares and inventories are set per game mode in the config. Please help!

**Comment by dumptruckman** [comment] 2017-06-07 14:59
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.

**Closed by dumptruckman** 2017-06-07 14:59 UTC
Labels: Assistance, Old - Open new issue if desired, Shares
