### ISSUE TITLE
An error which deletes the inventories of the players

### ISSUE THREAD

**Issue by Blamo27** [Multiverse/Multiverse-Inventories#281] opened 2016-02-28 15:31 UTC
> [16:25:59 ERROR]: Cannot load plugins/Multiverse-Inventories/worlds/world/_Criisis.json
> org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
>       at com.onarandombox.multiverseinventories.util.JsonConfiguration.loadFromString(JsonConfiguration.java:104) ~[?:?]
>       at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
>       at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
>       at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(JsonConfiguration.java:184) [Multiverse-Inventories-2.5.jar:?]
>       at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.<init>(EncodedJsonConfiguration.java:20) [Multiverse-Inventories-2.5.jar:?]
>       at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:77) [Multiverse-Inventories-2.5.jar:?]
>       at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:240) [Multiverse-Inventories-2.5.jar:?]
>       at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:30) [Multiverse-Inventories-2.5.jar:?]
>       at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:209) [Multiverse-Inventories-2.5.jar:?]

Any Fix ?

**Comment by xkitox** [comment] 2016-02-28 19:00
I am having this same issue.  I would love to find a solution!

**Comment by xkitox** [comment] 2016-03-06 18:38
Anyone have any idea why this is happening?

**Comment by sorifiend** [comment] 2016-03-06 21:34
When does it happen? What triggers it?

Have you tried building against the latest version of multiverse core and spigots 1.9 API rather than the older versions. After doing this its been running perfectly for me.

**Comment by Blamo27** [comment] 2016-03-06 21:39
Switched to PWI

**Comment by xkitox** [comment] 2016-03-06 21:51
Ah, thanks.

**Comment by dumptruckman** [comment] 2017-06-07 03:33
Closing as duplicate of #302.

**Closed by dumptruckman** 2017-06-07 03:33 UTC
Labels: Duplicate
