### ISSUE TITLE
Players able to take items from Creative to Survival

### ISSUE THREAD

**Issue by iMxAndyy** [Multiverse/Multiverse-Inventories#221] opened 2014-02-06 10:35 UTC
I have had a player on my server able to bring their items from creative world into the survival world
I am not sure how they have done this as they are not willing to tell me
from the console ive been able to see that they are doing /warp creative (a warp we made to get there), selecting the items he wants then doing /home to get back
I am not sure how he can keep items like this as i have tried everything i can think of but i cannot keep items like this.

I don't know if he had someone help him with this, as far as i know only he has been able to do this but two players have gotten the items he brought back so this other person may have assisted him or just been given the items by him, i can't know.

I am just wondering if there is a known bug with the plugin that causes this? or if anyone knows how this is being done?

**Comment by dumptruckman** [comment] 2017-06-07 14:13
Duplicate of #161 or #244.

**Closed by dumptruckman** 2017-06-07 14:13 UTC
